# Generated by Django 5.1.3 on 2024-12-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('fee', models.IntegerField()),
                ('age', models.IntegerField()),
                ('ward', models.CharField(max_length=50)),
                ('disease', models.CharField(max_length=255)),
            ],
        ),
    ]
